import { TOPICS } from "../../telemetry/topics.js";
import type { NumericTelemetry, TelemetryStateUpdate } from "../../telemetry/types.js";
const valid = (x: NumericTelemetry | undefined): x is NumericTelemetry & { value: number } => Boolean(x?.valid && x.value !== null && Number.isFinite(x.value));
const wrap180 = (a: number): number => { const v = ((a + 180) % 360 + 360) % 360 - 180; return v === -180 ? 180 : v; };
const DEPTH_SCALE = { min: -150, max: 10, step: 10 } as const;
export class RovHud extends HTMLElement {
  private unsubscribe: (() => void) | undefined; private heading = 0; private scaleRadius = new Map<string, number>();
  private connectTelemetry = (): void => { const s = window.rovCockpitTelemetry; if (s && !this.unsubscribe) this.unsubscribe = s.subscribe(u => this.consume(u)); };
  connectedCallback(): void { this.classList.add("rov-hud"); this.setAttribute("role", "img"); this.setAttribute("aria-label", "ROV roll, pitch, depth and heading HUD"); this.innerHTML = `<div class="rov-hud__roll-scale rov-hud__roll-scale--left" data-roll-scale="left"></div><div class="rov-hud__roll-scale rov-hud__roll-scale--right" data-roll-scale="right"></div><div class="rov-hud__attitude"><output class="rov-hud__roll" data-roll>r: --</output><canvas width="420" height="420" aria-hidden="true"></canvas><output class="rov-hud__pitch" data-pitch>p: --</output></div><div class="rov-hud__depth-scale" data-depth-scale></div><div class="rov-hud__heading"><output data-heading>---°</output><div data-heading-scale></div><b></b></div>`; this.renderScales(); this.drawAttitude(null, null); this.updateScaleOrigins(); this.connectTelemetry(); window.addEventListener("resize", this.updateScaleOrigins); window.addEventListener("rov-telemetry-ready", this.connectTelemetry); document.addEventListener("rov-instrument-style", this.applyStyle as EventListener); }
  disconnectedCallback(): void { this.unsubscribe?.(); this.unsubscribe = undefined; window.removeEventListener("resize", this.updateScaleOrigins); window.removeEventListener("rov-telemetry-ready", this.connectTelemetry); document.removeEventListener("rov-instrument-style", this.applyStyle as EventListener); }
  private applyStyle = (e: CustomEvent<{ target: string; style: { text: string; line: string; accent: string; lineWidth: number } }>): void => { if (e.detail.target !== "rov-hud") return; const s = e.detail.style; this.style.setProperty("--hud-text", s.text); this.style.setProperty("--hud-line", s.line); this.style.setProperty("--hud-accent", s.accent); this.style.setProperty("--hud-line-width", `${s.lineWidth}px`); };
  private consume(u: TelemetryStateUpdate): void { const n = u.state.numeric, r = n.get(TOPICS.roll), p = n.get(TOPICS.pitch), d = n.get(TOPICS.depth), h = n.get(TOPICS.heading), rv = valid(r) ? r.value : null, pv = valid(p) ? p.value : null; this.set("[data-roll]", rv === null ? "r: --" : `r: ${rv.toFixed(2)}`); this.set("[data-pitch]", pv === null ? "p: --" : `p: ${pv.toFixed(2)}`); this.drawAttitude(rv, pv); if (valid(h)) { this.heading = ((h.value % 360) + 360) % 360; this.set("[data-heading]", `${this.heading.toFixed(1)}°`); this.updateHeadingTape(); } else this.set("[data-heading]", "---°"); this.set("[data-depth-scale] [data-value]", valid(d) ? `${d.value.toFixed(1)} m` : "-- m"); if (valid(d)) this.alignDepthMark(d.value); const angle = rv === null ? 0 : -rv, pitchOffset = pv === null ? 0 : pv * this.pitchPixelsPerDegree(); this.querySelectorAll<HTMLElement>("[data-roll-scale]").forEach(x => { x.style.setProperty("--scale-rotate", `${angle}deg`); x.style.setProperty("--scale-pitch-offset", `${pitchOffset}px`); }); this.alignPitchScales(rv ?? 0, pv ?? 0); this.updateScaleVisibility(); this.updateDepthVisibility(); }
  private pitchPixelsPerDegree = (): number => { const scale = this.querySelector<HTMLElement>("[data-roll-scale]"); if (!scale) return 9.8; const marks = [...scale.querySelectorAll<HTMLElement>("span")], centre = marks.find(x => x.querySelector("b")?.textContent?.trim() === "0"), positiveTen = marks.find(x => x.querySelector("b")?.textContent?.trim() === "10"); if (!centre || !positiveTen) return 9.8; const centreY = centre.getBoundingClientRect().top + centre.getBoundingClientRect().height / 2, tenY = positiveTen.getBoundingClientRect().top + positiveTen.getBoundingClientRect().height / 2; return Math.abs(centreY - tenY) / 10; };
  private alignPitchScales = (roll: number, pitch: number): void => { const canvas = this.querySelector<HTMLCanvasElement>(".rov-hud__attitude canvas"); if (!canvas) return; const canvasRect = canvas.getBoundingClientRect(), centreX = canvasRect.left + canvasRect.width / 2, centreY = canvasRect.top + canvasRect.height / 2, angle = (-roll * Math.PI) / 180, pitchOffset = pitch * this.pitchPixelsPerDegree(); this.querySelectorAll<HTMLElement>("[data-roll-scale]").forEach(scale => { scale.style.setProperty("--scale-zero-y", "50%"); scale.style.setProperty("--scale-anchor-x", "0px"); scale.style.setProperty("--scale-anchor-y", "0px"); const mark = [...scale.querySelectorAll<HTMLElement>("span")].find(x => x.querySelector("b")?.textContent?.trim() === "0"); if (!mark) return; const rect = mark.getBoundingClientRect(), markCentreX = rect.left + rect.width / 2, markCentreY = rect.top + rect.height / 2, side = scale.dataset.rollScale === "left" ? -1 : 1, key = scale.dataset.rollScale ?? "right", radius = this.scaleRadius.get(key) ?? Math.abs(markCentreX - centreX); this.scaleRadius.set(key, radius); const lineX = centreX + side * radius * Math.cos(angle), lineY = centreY + side * radius * Math.sin(angle), desiredX = lineX - Math.sin(angle) * pitchOffset, desiredY = lineY + Math.cos(angle) * pitchOffset; scale.style.setProperty("--scale-anchor-x", `${desiredX - markCentreX}px`); scale.style.setProperty("--scale-anchor-y", `${desiredY - markCentreY}px`); }); };
  private alignDepthMark = (depth: number): void => { const scale = this.querySelector<HTMLElement>("[data-depth-scale]"); if (!scale) return; scale.style.setProperty("--depth-offset", "0px"); const target = Math.max(DEPTH_SCALE.min, Math.min(DEPTH_SCALE.max, Math.round(depth / DEPTH_SCALE.step) * DEPTH_SCALE.step)), mark = [...scale.querySelectorAll<HTMLElement>("span")].find(x => x.querySelector("b")?.textContent?.trim() === `${target} m`); if (!mark) return; const bounds = this.getBoundingClientRect(), rect = mark.getBoundingClientRect(), centre = rect.top + rect.height / 2; scale.style.setProperty("--depth-offset", `${bounds.top + bounds.height / 2 - centre}px`); };
  private updateScaleOrigins = (): void => { this.querySelectorAll<HTMLElement>("[data-roll-scale]").forEach(scale => { scale.style.transformOrigin = "center center"; }); const depth = this.querySelector<HTMLElement>("[data-depth-scale]"), zero = [...(depth?.querySelectorAll<HTMLElement>("span") ?? [])].find(x => x.querySelector("b")?.textContent?.trim() === "0 m"); if (depth && zero) { depth.style.setProperty("--depth-zero-offset", "0px"); const bounds = this.getBoundingClientRect(), zeroRect = zero.getBoundingClientRect(), zeroCentre = zeroRect.top + zeroRect.height / 2; depth.style.setProperty("--depth-zero-offset", `${zeroCentre - (bounds.top + bounds.height / 2)}px`); } this.updateScaleVisibility(); this.updateDepthVisibility(); };
  private updateScaleVisibility = (): void => { const top = window.innerHeight * .2, bottom = window.innerHeight * .8; this.querySelectorAll<HTMLElement>("[data-roll-scale] span").forEach(mark => { const rect = mark.getBoundingClientRect(), centre = rect.top + rect.height / 2; mark.style.visibility = centre >= top && centre <= bottom ? "visible" : "hidden"; }); };
  private updateDepthVisibility = (): void => { const top = window.innerHeight * .2, bottom = window.innerHeight * .8; this.querySelectorAll<HTMLElement>("[data-depth-scale] span").forEach(mark => { const rect = mark.getBoundingClientRect(), centre = rect.top + rect.height / 2; mark.style.visibility = centre >= top && centre <= bottom ? "visible" : "hidden"; }); };
  private drawAttitude(roll: number | null, pitch: number | null): void { const canvas = this.querySelector<HTMLCanvasElement>(".rov-hud__attitude canvas"), ctx = canvas?.getContext("2d"); if (!canvas || !ctx) return; const w = canvas.width, h = canvas.height, cx = w / 2, cy = h / 2, radius = Math.min(w, h) * .34, lineReach = Math.min(radius * 1.4, Math.min(cx, cy) - 4); ctx.clearRect(0, 0, w, h); ctx.save(); ctx.translate(cx, cy); ctx.rotate(-((roll ?? 0) * Math.PI) / 180); ctx.strokeStyle = getComputedStyle(this).getPropertyValue("--hud-line") || "#fff"; ctx.lineWidth = 3; ctx.lineCap = "butt"; ctx.beginPath(); ctx.arc(0, 0, radius, Math.PI * .75, Math.PI * 1.25); ctx.stroke(); ctx.beginPath(); ctx.arc(0, 0, radius, -Math.PI * .25, Math.PI * .25); ctx.stroke(); ctx.beginPath(); ctx.moveTo(-lineReach, 0); ctx.lineTo(-radius, 0); ctx.moveTo(radius, 0); ctx.lineTo(lineReach, 0); ctx.stroke(); ctx.restore(); }
  private updateHeadingTape(): void { this.querySelectorAll<HTMLElement>("[data-angle]").forEach(item => { const relative = wrap180(Number(item.dataset.angle) - this.heading); item.style.transform = `translateX(calc(-50% + ${relative * 4}px))`; item.style.opacity = Math.abs(relative) > 75 ? "0" : "1"; }); }
  private renderScales(): void { const labels = [30, 20, 10, 0, -10, -20, -30]; for (const side of ["left", "right"]) this.querySelector<HTMLElement>(`[data-roll-scale=${side}]`)!.innerHTML = labels.map(v => `<span class="${v === 0 ? "zero" : "dotted"}"><b>${v}</b><i></i></span>`).join(""); const depthLabels = Array.from({ length: Math.floor((DEPTH_SCALE.max - DEPTH_SCALE.min) / DEPTH_SCALE.step) + 1 }, (_, i) => DEPTH_SCALE.max - i * DEPTH_SCALE.step); this.querySelector<HTMLElement>("[data-depth-scale]")!.innerHTML = `<output data-value>-- m</output>${depthLabels.map(v => `<span class="${v === 0 ? "zero" : "dotted"}"><b>${v} m</b><i></i></span>`).join("")}`; this.querySelector<HTMLElement>("[data-heading-scale]")!.innerHTML = Array.from({ length: 73 }, (_, i) => { const a = i * 5 - 180, c = a % 45 === 0, names: Record<number, string> = { 0: "N", 45: "NE", 90: "E", 135: "SE", 180: "S", [-135]: "SW", [-90]: "W", [-45]: "NW" }; return `<span data-angle="${a}" class="${c ? "cardinal" : ""}"><i></i>${a % 15 === 0 ? `${a < 0 ? a + 360 : a}°` : ""}</span>`; }).join(""); this.updateHeadingTape(); }
  private set(selector: string, value: string): void { const e = this.querySelector<HTMLElement>(selector); if (e) e.textContent = value; }
}
customElements.get("rov-hud") || customElements.define("rov-hud", RovHud);
